# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_type', models.CharField(max_length=48)),
                ('picture_url', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('nearest_elementary', models.CharField(max_length=256)),
            ],
        ),
    ]
