# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20180415_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
